name: OWASP ZAP Security Scan (Staging)

on:
  workflow_dispatch: 

jobs:
  zap-scan:
    runs-on: self-hosted
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ==========================================
      # RUN OWASP ZAP BASELINE SCAN
      # ==========================================
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0 
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: http://${{ vars.STAGING_VM_HOST }} 
          fail_action: false 
          allow_issue_writing: false 
          
      # ==========================================
      # UPLOAD REPORT SEBAGAI ARTIFACT GUI
      # ==========================================
      - name: Upload ZAP Scan Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: owasp-zap-report-${{ github.run_number }}
          path: |
            zap_report.html
          if-no-files-found: warn
          retention-days: 14